# Generated by Django 3.0.4 on 2020-04-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='sub',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian'), ('Ham + Cheese', 'Ham + Cheese'), ('Meatball', 'Meatball'), ('Tuna', 'Tuna'), ('Turkey', 'Turkey'), ('Chicken Parmigiana', 'Chicken Parmigiana'), ('Eggplant Parmigiana', 'Eggplant Parmigiana'), ('Steak', 'Steak'), ('Steak + Cheese', 'Steak + Cheese'), ('Sausage, Peppers & Onions', 'Sausage, Peppers & Onions'), ('Hamburger', 'Hamburger'), ('Cheeseburger', 'Cheeseburger'), ('Fried Chicken', 'Fried Chicken'), ('Veggie', 'Veggie')], default='Cheese', max_length=30),
        ),
    ]
